### ISSUE TITLE
Service account 0 is outside the minsa: 1 and maxsa: 50 set in the config file with no 0.json in SA folder

### ISSUE THREAD

**Issue by crospa91** [Visorask/sarotate#12]
<14>May 11 11:01:31 sarotate: ====> BEGIN LOGGING
<14>May 11 11:01:31 sarotate:yyq_detect: Checking if version is 3.4.1.
<14>May 11 11:01:31 sarotate:yyq_detect: yyq is at version 3.4.1.
<14>May 11 11:01:31 sarotate:yyq_detect: Version check complete.
<11>May 11 11:01:32 sarotate:array_combine: Service account 0 is outside the minsa: 1 and maxsa: 50 set in the config file.
<11>May 11 11:01:32 sarotate:array_combine: Correct this and run the script again.
<11>May 11 11:01:32 sarotate:array_combine: The script will now exit.

this is the log I'm receiving.

why the script is trying to use the 0.json instead of 1.json?

I'm tried to make a workaround, copying the 1.json to 0.json and the script starts, but it does use the 2.json for all remotes, and not only for the first one in the list, contrary to what is set in config.yml.

Funny part is that I have another machine where the script it's working without a problem, so I have no idea why on this ubuntu linux is creating so many issues

**Comment by Visorask** [comment]
Try setting the minjs to 2.
