### ISSUE TITLE
Keep Track of Used SA's

### ISSUE THREAD

**Issue by sbcrumb** [Visorask/sarotate#3]
I have noticed that it works well, until you either restart the process or the server, at which point it will go back to using the first SA in the list, which could in fact have hit a limit. Would be nice to keep a list of used ones and not repeat them till 24hrs has passed. Then allow that SA to go back into the rotation.

**Comment by Visorask** [comment]
I can add this in, just gotta figure out how I want to do it.

**Comment by sbcrumb** [comment]
Any luck with this

**Comment by Visorask** [comment]
Am working on a solution for this it will be ready in a few days.
