### ISSUE TITLE
Need help with setting up  the config 

### ISSUE THREAD

**Issue by xd003** [Visorask/sarotate#8]
First of all thanks a lot for the work on this project . Just trying it out for the very first time
At the moment , I don't need sa rotation for rclone mount . I primarily need it for all other rclone operations like copy ,sync etc

1) So my first question was will i have to setup the config file bit differently to make copy and sync work with sarotate.

2) Secondly i don't quite understand the port thing at the very bottom of the sarotate config
Lets say i have 2 remotes named - library1 and library2 . And i need to copy from library1 to library2 , then i need to add them both in the remote option at bottom of config correct ? Now what's should be the port for these ?

3) After the sarotate service is running well  , how do i run the rclone copy command to make it use sarotate ?
```rclone copy library1: library2: --drive-server-side-across-configs``` running the copy command normally like this will utilise sarotate or i will have to make some changes to it ?

Confused regarding all this , can you please help regarding the same

**Comment by Visorask** [comment]
This project is not meant for uploading and downloading it is mainly meant to keep from getting API banned. You will want to look into some of the other things that are out there such as:

https://github.com/l3uddz/crop
https://github.com/88lex/sasync/tree/master/utils

Those 2 can do everything you need.

**Comment by xd003** [comment]
@Visorask 
Thank you for clearing the confusion , i will check out those projects . Cheers
